name: Deploy to master
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure AWS credentials

        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: AWS Deploy
        run: |
          aws s3 sync . s3://${{ secrets.AWS_BUCKET }} --delete --exclude='.git'
      - name: AWS Invalidate
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_ID }} --paths "/*"
